In [1]:
import numpy as np

In [2]:
n1 = input("Enter a name :")
n2 = input("Enter a name :")
n3 = input("Enter a name :")
n4 = input("Enter a name :")
n5 = input("Enter a name :")
list1 = [n1 , n2 , n3 , n4 , n5]
list1

Enter a name :armin
Enter a name :lili
Enter a name :ope
Enter a name :yas
Enter a name :mim


['armin', 'lili', 'ope', 'yas', 'mim']

In [4]:
armin = []
for i in range(10):
    nomre = float(input("is a nomre armin:"))
    armin.append(nomre)
armin = np.array(armin)
armin

is a nomre armin:20
is a nomre armin:18
is a nomre armin:20
is a nomre armin:19
is a nomre armin:28
is a nomre armin:10
is a nomre armin:20
is a nomre armin:19
is a nomre armin:20
is a nomre armin:13


array([20., 18., 20., 19., 28., 10., 20., 19., 20., 13.])

In [15]:
m1 = np.mean(armin)
armin_1 = [n1,m1]
armin_1

['armin', 18.7]

In [7]:
lili = []
for i in range(10):
    nomre_1 = float(input("is a nomre lili:"))
    lili.append(nomre_1)
lili = np.array(lili)
lili

is a nomre lili:20
is a nomre lili:20
is a nomre lili:20
is a nomre lili:19
is a nomre lili:20
is a nomre lili:20
is a nomre lili:20
is a nomre lili:20
is a nomre lili:20
is a nomre lili:20


array([20., 20., 20., 19., 20., 20., 20., 20., 20., 20.])

In [16]:
m2 = np.mean(lili)
lili_1 = [n2,m2]
lili_1

['lili', 19.9]

In [9]:
ope = []
for i in range(10):
    nomre = float(input("is a nomre ope:"))
    ope.append(nomre)
ope = np.array(ope)
ope

is a nomre ope:19
is a nomre ope:12
is a nomre ope:14
is a nomre ope:16
is a nomre ope:18
is a nomre ope:19
is a nomre ope:20
is a nomre ope:20
is a nomre ope:12
is a nomre ope:14


array([19., 12., 14., 16., 18., 19., 20., 20., 12., 14.])

In [17]:
m3 = np.mean(ope)
ope_1 = [n3,m3]
ope_1

['ope', 16.4]

In [12]:
yas = []
for i in range(10):
    nomre = float(input("is a nomre yas:"))
    yas.append(nomre)
yas = np.array(yas)
yas

is a nomre yas:20
is a nomre yas:19
is a nomre yas:20
is a nomre yas:20
is a nomre yas:18
is a nomre yas:27
is a nomre yas:2
is a nomre yas:13
is a nomre yas:20
is a nomre yas:3


array([20., 19., 20., 20., 18., 27.,  2., 13., 20.,  3.])

In [18]:
m4 = np.mean(yas)
yas_1 = [n4,m4]
yas_1

['yas', 16.2]

In [19]:
mim = []
for i in range(10):
    nomre = float(input("is a nomre mim:"))
    mim.append(nomre)
mim = np.array(mim)
mim

is a nomre mim:20
is a nomre mim:12
is a nomre mim:14
is a nomre mim:20
is a nomre mim:20
is a nomre mim:15
is a nomre mim:20
is a nomre mim:12
is a nomre mim:1
is a nomre mim:13


array([20., 12., 14., 20., 20., 15., 20., 12.,  1., 13.])

In [21]:
m5 = np.mean(yas)
mim = [n5,m5]
mim

['mim', 16.2]

In [ ]:
mim , yas_1 , armin_